spring:
  neo4j:

     uri: neo4j+s://9efe98a7.databases.neo4j.io
     authentication:
       username: neo4j
       password: 9lZh8hvrG4sdOdas9Sx_vnf6Alc6v0FMtx-dJaT4awo
server:
  port: 8081
#    uri: bolt://localhost:7687   # for local DB connection
#      username: neo4j
#      password: rahul123           # these are the credentials for local
